// sync-web-libs — inject lib/*.alg sources into the web pages' library
// registry (B-092 U4). The browser runtime resolves `use NAME` through
// Allegro.registerLibrary(name, source); before this script the pages
// carried hand-pasted, drifting copies (and the sandbox pages carried
// NONE — `use contracts` presets failed on the deployed sandbox).
//
// Each target file holds a marked region; this script regenerates the
// region from the DISK libs (the same sources the CLI and test suite
// load), then verifies the generated literals decode byte-identically.
//
//   npx tsx scripts/sync-web-libs.ts        # rewrite + verify
//   npx tsx scripts/sync-web-libs.ts --check  # verify only (CI-able)
//
// Run it whenever a lib in WEB_LIBS changes.

import * as fs from "fs";

const WEB_LIBS = ["pow", "match_expr", "invariants", "contracts", "effects", "units"];
const TARGETS = ["website/index.html", "website/sandbox.html", "web/sandbox.html"];
const BEGIN = "// --- BEGIN LIB REGISTRY (generated by scripts/sync-web-libs.ts — do not edit by hand) ---";
const END   = "// --- END LIB REGISTRY ---";

function escapeForTemplateLiteral(src: string): string {
  return src.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function decodeTemplateLiteral(escaped: string): string {
  return escaped.replace(/\\\$\{/g, "${").replace(/\\`/g, "`").replace(/\\\\/g, "\\");
}

function generateRegion(): string {
  const parts: string[] = [BEGIN];
  for (const name of WEB_LIBS) {
    const src = fs.readFileSync(`lib/${name}.alg`, "utf-8");
    parts.push(`Allegro.registerLibrary('${name}', \`${escapeForTemplateLiteral(src)}\`);`);
  }
  parts.push(END);
  return parts.join("\n");
}

function verifyRegion(html: string, file: string): void {
  const region = html.slice(html.indexOf(BEGIN), html.indexOf(END));
  for (const name of WEB_LIBS) {
    const anchor = `Allegro.registerLibrary('${name}', \``;
    const start = region.indexOf(anchor);
    if (start < 0) throw new Error(`${file}: lib '${name}' missing from registry region`);
    const bodyStart = start + anchor.length;
    const bodyEnd = region.indexOf("`);", bodyStart);
    const decoded = decodeTemplateLiteral(region.slice(bodyStart, bodyEnd));
    const disk = fs.readFileSync(`lib/${name}.alg`, "utf-8");
    if (decoded !== disk) {
      throw new Error(`${file}: lib '${name}' drifted from lib/${name}.alg — rerun sync-web-libs`);
    }
  }
}

const checkOnly = process.argv.includes("--check");
const region = generateRegion();

for (const file of TARGETS) {
  let html = fs.readFileSync(file, "utf-8");
  const b = html.indexOf(BEGIN);
  const e = html.indexOf(END);
  if (b < 0 || e < 0) throw new Error(`${file}: registry markers not found — add them once by hand`);
  if (!checkOnly) {
    html = html.slice(0, b) + region + html.slice(e + END.length);
    fs.writeFileSync(file, html);
  }
  verifyRegion(fs.readFileSync(file, "utf-8"), file);
  console.log(`${checkOnly ? "verified" : "synced"}: ${file}`);
}
