// @ts-nocheck
// ═══════════════════════════════════════════════════════════════════════════════
// Standalone Parser Runtime
// Generated by parser-generator — this file is self-contained with no imports.
// ═══════════════════════════════════════════════════════════════════════════════

// ─── Types ──────────────────────────────────────────────────────────────────────

interface TextLocation {
  index: number;
  line: number;
  column: number;
}

interface ParseError {
  message: string;
  start: TextLocation;
  end: TextLocation;
}

interface ParseResult {
  tree: SyntaxTreeNode;
  errors: ParseError[];
}

// ─── SyntaxTreeNode ─────────────────────────────────────────────────────────────

class SyntaxTreeNode {
  element: GrammarElement;
  start: TextLocation;
  end: TextLocation;
  text: string;
  parent: SyntaxTreeNode | null;
  children: SyntaxTreeNode[];
  [key: string]: unknown;

  constructor(
    element: GrammarElement,
    start: TextLocation,
    end: TextLocation,
    text: string,
    children: SyntaxTreeNode[] = [],
  ) {
    this.element = element;
    this.start = start;
    this.end = end;
    this.text = text;
    this.parent = null;
    this.children = children;
  }
}

// ─── Grammar Elements ───────────────────────────────────────────────────────────

type AttributeType = typeof String | typeof Number | typeof Boolean | typeof Object;

interface AttributeDefinition {
  name: string;
  type: AttributeType;
  evaluate?: (node: SyntaxTreeNode) => unknown;
}

type FinalizeFunction = (node: SyntaxTreeNode) => SyntaxTreeNode | void;

type ElementReference = GrammarElement | string;

abstract class GrammarElement {
  name: string | null = null;
  grammar: unknown = null;
  readonly attributes: Map<string, AttributeDefinition> = new Map();
  finalizeFunction: FinalizeFunction | null = null;

  attribute(name: string, type: AttributeType, evaluate?: (node: SyntaxTreeNode) => unknown): this {
    this.attributes.set(name, { name, type, evaluate });
    return this;
  }

  finalize(fn: FinalizeFunction): this {
    this.finalizeFunction = fn;
    return this;
  }
}

class Terminal extends GrammarElement {
  readonly pattern: RegExp | string;

  constructor(pattern: RegExp | string) {
    super();
    this.pattern = pattern;
  }
}

type SpecialTerminalKind = 'EndOfFile' | 'Indent' | 'Unindent' | 'EndOfLine';

class SpecialTerminal extends GrammarElement {
  readonly kind: SpecialTerminalKind;

  private static readonly instances = new Map<SpecialTerminalKind, SpecialTerminal>();

  private constructor(kind: SpecialTerminalKind) {
    super();
    this.kind = kind;
    this.name = kind;
  }

  static of(kind: SpecialTerminalKind): SpecialTerminal {
    let instance = SpecialTerminal.instances.get(kind);
    if (!instance) {
      instance = new SpecialTerminal(kind);
      SpecialTerminal.instances.set(kind, instance);
    }
    return instance;
  }
}

class Phrase extends GrammarElement {
  readonly elements: GrammarElement[];

  constructor(elements: GrammarElement[]) {
    super();
    this.elements = elements;
  }
}

class Disjunction extends GrammarElement {
  readonly alternatives: GrammarElement[];

  constructor(alternatives: GrammarElement[]) {
    super();
    this.alternatives = alternatives;
  }

  add(alternative: GrammarElement): this {
    this.alternatives.push(alternative);
    return this;
  }
}

interface RepeatOptions {
  min?: number;
  max?: number;
  delimiter?: ElementReference;
  includeDelimiter?: boolean;
}

class Repetition extends GrammarElement {
  readonly element: GrammarElement;
  readonly min: number;
  readonly max: number;
  readonly delimiter: GrammarElement | null;
  readonly includeDelimiter: boolean;

  constructor(element: GrammarElement, min: number, max: number, delimiter: GrammarElement | null, includeDelimiter: boolean) {
    super();
    this.element = element;
    this.min = min;
    this.max = max;
    this.delimiter = delimiter;
    this.includeDelimiter = includeDelimiter;
  }
}

class Optional extends GrammarElement {
  readonly element: GrammarElement;

  constructor(element: GrammarElement) {
    super();
    this.element = element;
  }
}

// ─── Grammar ────────────────────────────────────────────────────────────────────

interface GrammarOptions {
  whitespace?: RegExp | RegExp[];
  comments?: RegExp | RegExp[];
  blockIndent?: boolean;
}

interface OperatorPrecedenceLevel {
  operators: GrammarElement[];
  associativity: 'left' | 'right' | 'none';
}

class Grammar {
  readonly options: GrammarOptions;
  target: GrammarElement | null = null;
  readonly precedenceLevels: OperatorPrecedenceLevel[] = [];
  private readonly elements: GrammarElement[] = [];
  private readonly namedElements: Map<string, GrammarElement> = new Map();
  private readonly fixedStringTerminals: Map<string, Terminal> = new Map();

  constructor(options?: GrammarOptions) {
    this.options = options ?? {};
  }

  terminal(pattern: RegExp | string, name?: string): Terminal {
    const t = new Terminal(pattern);
    return this.register(t, name);
  }

  phrase(elements: ElementReference[], name?: string): Phrase {
    const resolved = elements.map(e => this.resolve(e));
    const p = new Phrase(resolved);
    return this.register(p, name);
  }

  disjunction(alternatives: ElementReference[], name?: string): Disjunction {
    const resolved = alternatives.map(a => this.resolve(a));
    const d = new Disjunction(resolved);
    return this.register(d, name);
  }

  repeat(element: ElementReference, options?: RepeatOptions): Repetition {
    const resolved = this.resolve(element);
    const delimiter = options?.delimiter != null ? this.resolve(options.delimiter) : null;
    const r = new Repetition(
      resolved,
      options?.min ?? 0,
      options?.max ?? Infinity,
      delimiter,
      options?.includeDelimiter ?? false,
    );
    return this.register(r);
  }

  optional(element: ElementReference): Optional {
    const resolved = this.resolve(element);
    const o = new Optional(resolved);
    return this.register(o);
  }

  precedence(operators: ElementReference[], associativity: 'left' | 'right' | 'none' = 'left'): this {
    const resolved = operators.map(op => this.resolve(op));
    this.precedenceLevels.push({ operators: resolved, associativity });
    return this;
  }

  get(name: string): GrammarElement {
    const el = this.namedElements.get(name);
    if (!el) {
      throw new Error(`Grammar element '${name}' not found`);
    }
    return el;
  }

  resolve(ref: ElementReference): GrammarElement {
    if (ref instanceof GrammarElement) {
      return ref;
    }
    let t = this.fixedStringTerminals.get(ref);
    if (!t) {
      t = new Terminal(ref);
      t.grammar = this;
      this.fixedStringTerminals.set(ref, t);
      this.elements.push(t);
    }
    return t;
  }

  private register<T extends GrammarElement>(element: T, name?: string): T {
    element.grammar = this;
    this.elements.push(element);
    if (name) {
      if (this.namedElements.has(name)) {
        throw new Error(`Duplicate grammar element name: '${name}'`);
      }
      element.name = name;
      this.namedElements.set(name, element);
    }
    return element;
  }
}

// ─── Earley Parser ──────────────────────────────────────────────────────────────

interface EarleyRule {
  element: GrammarElement;
  symbols: GrammarElement[];
  altIndex: number;
}

interface VirtualToken {
  kind: 'Indent' | 'Unindent' | 'EndOfLine';
  offset: number;
}

interface EarleyItem {
  rule: EarleyRule;
  dot: number;
  origin: number;
}

let nextElementId = 0;
const elementIdMap = new WeakMap<GrammarElement, number>();

function getElementId(element: GrammarElement): number {
  let id = elementIdMap.get(element);
  if (id === undefined) {
    id = nextElementId++;
    elementIdMap.set(element, id);
  }
  return id;
}

let nextRuleId = 0;
const ruleIdMap = new WeakMap<EarleyRule, number>();

function getRuleId(rule: EarleyRule): number {
  let id = ruleIdMap.get(rule);
  if (id === undefined) {
    id = nextRuleId++;
    ruleIdMap.set(rule, id);
  }
  return id;
}

function itemKey(item: EarleyItem): string {
  const ruleId = getRuleId(item.rule);
  return `${ruleId}:${item.dot}:${item.origin}`;
}

class EarleyParser {
  private grammar: Grammar;
  private input: string;
  private target: GrammarElement;
  private rulesByElement: Map<GrammarElement, EarleyRule[]> = new Map();
  private chart: EarleyItem[][] = [];
  private chartKeys: Set<string>[] = [];
  private positions: number[] = [];
  private terminalMatches: Map<number, { element: GrammarElement; text: string }[]> = new Map();
  private completions: Map<string, EarleyRule[]> = new Map();
  private wsPatterns: RegExp[] = [];
  private commentPatterns: RegExp[] = [];
  private blockIndent: boolean;
  private virtualTokens: VirtualToken[] = [];
  private skippableNewlines: Set<number> = new Set();
  private virtualTokensByOffset: Map<string, VirtualToken[]> = new Map();
  private furthestPos: number = 0;
  private furthestInputOffset: number = 0;
  private expectedAtFurthest: Set<string> = new Set();
  private augmentedStart!: GrammarElement;
  private disambiguationCache: Map<string, EarleyRule> = new Map();
  private reconstructionCache: Map<string, SyntaxTreeNode | null> = new Map();
  private vtConsumed: Map<string, number> = new Map();
  private vtConsumedAtChartPos: Set<string> = new Set();
  private additionalAlternatives: Map<GrammarElement, GrammarElement[]>;

  constructor(grammar: Grammar, input: string, target: GrammarElement, additionalAlternatives?: Map<GrammarElement, GrammarElement[]>) {
    this.grammar = grammar;
    this.input = input;
    this.target = target;
    this.additionalAlternatives = additionalAlternatives ?? new Map();
    this.blockIndent = grammar.options.blockIndent ?? false;
    this.compileWhitespace();
    if (this.blockIndent) {
      this.preprocessBlockIndent();
    }
    this.compileRules();
  }

  private compileWhitespace(): void {
    const ws = this.grammar.options.whitespace;
    if (ws) {
      const patterns = Array.isArray(ws) ? ws : [ws];
      this.wsPatterns = patterns.map(p => new RegExp(p.source, 'y'));
    } else if (this.blockIndent) {
      this.wsPatterns = [/[ \t]*/y];
    }
    const comments = this.grammar.options.comments;
    if (comments) {
      const patterns = Array.isArray(comments) ? comments : [comments];
      this.commentPatterns = patterns.map(p => new RegExp(p.source, 'y'));
    }
  }

  private preprocessBlockIndent(): void {
    const lines = this.input.split(/\n/);
    const indentStack = [0];
    let offset = 0;
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const trimmed = line.replace(/^[ \t]*/, '');
      if (trimmed.length === 0) {
        const nlOffset = offset + line.length;
        if (nlOffset < this.input.length) {
          this.skippableNewlines.add(nlOffset);
        }
        offset += line.length + 1;
        continue;
      }
      if (this.commentPatterns.length > 0) {
        let isComment = false;
        for (const pat of this.commentPatterns) {
          pat.lastIndex = 0;
          const m = pat.exec(trimmed);
          if (m && m[0].length === trimmed.length) {
            isComment = true;
            break;
          }
        }
        if (isComment) {
          const nlOffset = offset + line.length;
          if (nlOffset < this.input.length) {
            this.skippableNewlines.add(nlOffset);
          }
          offset += line.length + 1;
          continue;
        }
      }
      const indentLen = line.length - trimmed.length;
      const contentOffset = offset + indentLen;
      const currentIndent = indentStack[indentStack.length - 1];
      if (indentLen > currentIndent) {
        indentStack.push(indentLen);
        this.addVirtualToken({ kind: 'Indent', offset: contentOffset });
      } else {
        while (indentStack.length > 1 && indentLen < indentStack[indentStack.length - 1]) {
          indentStack.pop();
          this.addVirtualToken({ kind: 'Unindent', offset: contentOffset });
        }
      }
      const lineEndOffset = offset + line.length;
      this.addVirtualToken({ kind: 'EndOfLine', offset: lineEndOffset });
      offset += line.length + 1;
    }
    while (indentStack.length > 1) {
      indentStack.pop();
      this.addVirtualToken({ kind: 'Unindent', offset: this.input.length });
    }
  }

  private addVirtualToken(vt: VirtualToken): void {
    this.virtualTokens.push(vt);
    const key = `${vt.kind}:${vt.offset}`;
    let list = this.virtualTokensByOffset.get(key);
    if (!list) {
      list = [];
      this.virtualTokensByOffset.set(key, list);
    }
    list.push(vt);
  }

  private compileRules(): void {
    this.augmentedStart = new Phrase([this.target]);
    (this.augmentedStart as any).name = '__start__';
    this.addRule({ element: this.augmentedStart, symbols: [this.target], altIndex: 0 });
    const visited = new Set<GrammarElement>();
    this.compileElement(this.target, visited);
  }

  private compileElement(element: GrammarElement, visited: Set<GrammarElement>): void {
    if (visited.has(element)) return;
    visited.add(element);
    if (element instanceof Phrase) {
      this.addRule({ element, symbols: [...element.elements], altIndex: 0 });
      for (const child of element.elements) {
        this.compileElement(child, visited);
      }
    } else if (element instanceof Disjunction) {
      for (let i = 0; i < element.alternatives.length; i++) {
        const alt = element.alternatives[i];
        this.addRule({ element, symbols: [alt], altIndex: i });
        this.compileElement(alt, visited);
      }
      // Check for grammar extensions (additional alternatives without mutating base)
      const extras = this.additionalAlternatives.get(element);
      if (extras) {
        for (let j = 0; j < extras.length; j++) {
          this.addRule({ element, symbols: [extras[j]], altIndex: element.alternatives.length + j });
          this.compileElement(extras[j], visited);
        }
      }
    } else if (element instanceof Repetition) {
      this.compileRepetition(element, visited);
    } else if (element instanceof Optional) {
      this.addRule({ element, symbols: [], altIndex: 0 });
      this.addRule({ element, symbols: [element.element], altIndex: 1 });
      this.compileElement(element.element, visited);
    }
  }

  private compileRepetition(rep: Repetition, visited: Set<GrammarElement>): void {
    if (rep.delimiter) {
      if (rep.min === 0) {
        this.addRule({ element: rep, symbols: [], altIndex: 0 });
        this.addRule({ element: rep, symbols: [rep.element], altIndex: 1 });
        this.addRule({ element: rep, symbols: [rep, rep.delimiter, rep.element], altIndex: 2 });
      } else {
        this.addRule({ element: rep, symbols: [rep.element], altIndex: 0 });
        this.addRule({ element: rep, symbols: [rep, rep.delimiter, rep.element], altIndex: 1 });
      }
      this.compileElement(rep.delimiter, visited);
    } else {
      if (rep.min === 0) {
        this.addRule({ element: rep, symbols: [], altIndex: 0 });
        this.addRule({ element: rep, symbols: [rep, rep.element], altIndex: 1 });
      } else {
        this.addRule({ element: rep, symbols: [rep.element], altIndex: 0 });
        this.addRule({ element: rep, symbols: [rep, rep.element], altIndex: 1 });
      }
    }
    this.compileElement(rep.element, visited);
  }

  private addRule(rule: EarleyRule): void {
    let rules = this.rulesByElement.get(rule.element);
    if (!rules) {
      rules = [];
      this.rulesByElement.set(rule.element, rules);
    }
    rules.push(rule);
  }

  private isNonterminal(element: GrammarElement): boolean {
    return (
      element instanceof Phrase ||
      element instanceof Disjunction ||
      element instanceof Repetition ||
      element instanceof Optional
    );
  }

  private tryMatchTerminal(element: GrammarElement, inputOffset: number, chartPos?: number): string | null {
    if (element instanceof Terminal) {
      if (typeof element.pattern === 'string') {
        if (this.input.startsWith(element.pattern, inputOffset)) {
          return element.pattern;
        }
        return null;
      } else {
        const regex = new RegExp(element.pattern.source, 'y');
        regex.lastIndex = inputOffset;
        const m = regex.exec(this.input);
        return m ? m[0] : null;
      }
    } else if (element instanceof SpecialTerminal) {
      if (element.kind === 'EndOfFile') {
        return inputOffset >= this.input.length ? '' : null;
      }
      if (this.blockIndent) {
        return this.tryMatchVirtualToken(element.kind, inputOffset, chartPos ?? 0);
      }
      return null;
    }
    return null;
  }

  private tryMatchVirtualToken(kind: string, offset: number, chartPos: number): string | null {
    const totalKey = `${kind}:${offset}`;
    const posKey = `${chartPos}:${kind}:${offset}`;
    let available = 0;
    for (const vt of this.virtualTokens) {
      if (vt.kind === kind && vt.offset === offset) available++;
    }
    if (available === 0) return null;
    const consumed = this.vtConsumed.get(totalKey) ?? 0;
    if (!this.vtConsumedAtChartPos.has(posKey)) {
      if (consumed >= available) return null;
      this.vtConsumedAtChartPos.add(posKey);
      this.vtConsumed.set(totalKey, consumed + 1);
    }
    if (kind === 'EndOfLine' && offset < this.input.length) return '\n';
    return '';
  }

  private skipWhitespace(offset: number): number {
    if (this.wsPatterns.length === 0 && this.commentPatterns.length === 0
        && this.skippableNewlines.size === 0) {
      return offset;
    }
    let pos = offset;
    let changed = true;
    while (changed) {
      changed = false;
      for (const pat of this.wsPatterns) {
        pat.lastIndex = pos;
        const m = pat.exec(this.input);
        if (m && m[0].length > 0) {
          pos += m[0].length;
          changed = true;
        }
      }
      for (const pat of this.commentPatterns) {
        pat.lastIndex = pos;
        const m = pat.exec(this.input);
        if (m && m[0].length > 0) {
          pos += m[0].length;
          changed = true;
        }
      }
      if (this.skippableNewlines.has(pos)) {
        pos++;
        changed = true;
      }
    }
    return pos;
  }

  private locationFromOffset(offset: number): TextLocation {
    let line = 1;
    let column = 1;
    for (let i = 0; i < offset && i < this.input.length; i++) {
      if (this.input[i] === '\n') {
        line++;
        column = 1;
      } else {
        column++;
      }
    }
    return { index: offset, line, column };
  }

  parse(): ParseResult {
    const startPos = this.skipWhitespace(0);
    this.positions = [startPos];
    this.chart = [[]];
    this.chartKeys = [new Set()];
    const startRules = this.rulesByElement.get(this.augmentedStart);
    if (startRules) {
      for (const rule of startRules) {
        this.addToChart(0, { rule, dot: 0, origin: 0 });
      }
    }
    let chartPos = 0;
    while (chartPos < this.chart.length) {
      const items = this.chart[chartPos];
      let i = 0;
      while (i < items.length) {
        const item = items[i];
        if (item.dot < item.rule.symbols.length) {
          const nextSymbol = item.rule.symbols[item.dot];
          if (this.isNonterminal(nextSymbol)) {
            this.predict(nextSymbol, chartPos);
          } else {
            this.scan(item, chartPos);
          }
        } else {
          this.complete(item, chartPos);
        }
        i++;
      }
      chartPos++;
    }
    return this.buildResult();
  }

  private addToChart(pos: number, item: EarleyItem): boolean {
    const key = itemKey(item);
    if (this.chartKeys[pos].has(key)) return false;
    this.chartKeys[pos].add(key);
    this.chart[pos].push(item);
    return true;
  }

  private predict(element: GrammarElement, chartPos: number): void {
    const rules = this.rulesByElement.get(element);
    if (!rules) return;
    for (const rule of rules) {
      this.addToChart(chartPos, { rule, dot: 0, origin: chartPos });
      if (rule.symbols.length === 0) {
        this.recordCompletion(rule.element, chartPos, chartPos, rule);
        this.completeElement(rule.element, chartPos, chartPos);
      }
    }
  }

  private scan(item: EarleyItem, chartPos: number): void {
    const nextSymbol = item.rule.symbols[item.dot];
    const inputOffset = this.positions[chartPos];
    const matchText = this.tryMatchTerminal(nextSymbol, inputOffset, chartPos);
    if (matchText === null) {
      if (chartPos >= this.furthestPos) {
        if (chartPos > this.furthestPos) {
          this.furthestPos = chartPos;
          this.furthestInputOffset = inputOffset;
          this.expectedAtFurthest.clear();
        }
        this.expectedAtFurthest.add(this.describeTerminal(nextSymbol));
      }
      return;
    }
    const nextChartPos = chartPos + 1;
    if (this.chart.length <= nextChartPos) {
      const nextOffset = inputOffset + matchText.length;
      const skippedOffset = this.skipWhitespace(nextOffset);
      this.positions.push(skippedOffset);
      this.chart.push([]);
      this.chartKeys.push(new Set());
    }
    this.recordTerminalMatch(chartPos, nextSymbol, matchText);
    this.addToChart(nextChartPos, {
      rule: item.rule,
      dot: item.dot + 1,
      origin: item.origin,
    });
  }

  private complete(item: EarleyItem, chartPos: number): void {
    const completedElement = item.rule.element;
    this.recordCompletion(completedElement, item.origin, chartPos, item.rule);
    this.completeElement(completedElement, item.origin, chartPos);
  }

  private completeElement(completedElement: GrammarElement, origin: number, chartPos: number): void {
    const waitingItems = [...this.chart[origin]];
    for (const waitingItem of waitingItems) {
      if (waitingItem.dot >= waitingItem.rule.symbols.length) continue;
      if (waitingItem.rule.symbols[waitingItem.dot] !== completedElement) continue;
      this.addToChart(chartPos, {
        rule: waitingItem.rule,
        dot: waitingItem.dot + 1,
        origin: waitingItem.origin,
      });
    }
  }

  private recordTerminalMatch(chartPos: number, element: GrammarElement, text: string): void {
    let list = this.terminalMatches.get(chartPos);
    if (!list) {
      list = [];
      this.terminalMatches.set(chartPos, list);
    }
    if (!list.some(m => m.element === element && m.text === text)) {
      list.push({ element, text });
    }
  }

  private recordCompletion(element: GrammarElement, origin: number, end: number, rule: EarleyRule): void {
    const key = `${getElementId(element)}:${origin}:${end}`;
    let rules = this.completions.get(key);
    if (!rules) {
      rules = [];
      this.completions.set(key, rules);
    }
    if (!rules.includes(rule)) {
      rules.push(rule);
    }
  }

  private buildResult(): ParseResult {
    const lastChartPos = this.chart.length - 1;
    let foundEnd = -1;
    for (let pos = lastChartPos; pos >= 0; pos--) {
      const key = `${getElementId(this.augmentedStart)}:0:${pos}`;
      if (this.completions.has(key)) {
        foundEnd = pos;
        break;
      }
    }
    if (foundEnd === -1) {
      const errorLoc = this.locationFromOffset(this.furthestInputOffset);
      const expected = [...this.expectedAtFurthest];
      const msg = expected.length > 0
        ? `Expected ${expected.join(' or ')} at line ${errorLoc.line}, column ${errorLoc.column}`
        : `Unexpected input at line ${errorLoc.line}, column ${errorLoc.column}`;
      const errorElement = new Terminal('');
      (errorElement as any).name = '__error__';
      const startLoc = this.locationFromOffset(0);
      const endLoc = this.locationFromOffset(this.input.length);
      const errorNode = new SyntaxTreeNode(errorElement, startLoc, endLoc, this.input);
      return { tree: errorNode, errors: [{ message: msg, start: errorLoc, end: errorLoc }] };
    }
    const errors: ParseError[] = [];
    const endOffset = this.positions[foundEnd] ?? this.input.length;
    const afterParse = this.skipWhitespace(endOffset);
    if (afterParse < this.input.length) {
      const loc = this.locationFromOffset(afterParse);
      errors.push({
        message: `Unexpected input at line ${loc.line}, column ${loc.column}`,
        start: loc,
        end: this.locationFromOffset(this.input.length),
      });
    }
    const tree = this.reconstruct(this.augmentedStart, 0, foundEnd);
    if (!tree) {
      const errorLoc = this.locationFromOffset(0);
      const errorElement = new Terminal('');
      (errorElement as any).name = '__error__';
      const endLoc = this.locationFromOffset(this.input.length);
      return {
        tree: new SyntaxTreeNode(errorElement, errorLoc, endLoc, this.input),
        errors: [{ message: `Failed to reconstruct parse tree`, start: errorLoc, end: endLoc }],
      };
    }
    if (tree.children.length === 1) {
      const inner = tree.children[0];
      inner.parent = null;
      return { tree: inner, errors };
    }
    return { tree, errors };
  }

  private reconstruct(element: GrammarElement, start: number, end: number): SyntaxTreeNode | null {
    const cacheKey = `${getElementId(element)}:${start}:${end}`;
    if (this.reconstructionCache.has(cacheKey)) {
      const cached = this.reconstructionCache.get(cacheKey)!;
      return cached ? this.cloneTree(cached) : null;
    }
    this.reconstructionCache.set(cacheKey, null);
    const completionKey = `${getElementId(element)}:${start}:${end}`;
    const rules = this.completions.get(completionKey);
    if (!rules) return null;
    const rule = this.disambiguateRules(element, rules, start, end);
    if (!rule) return null;
    const children = this.reconstructChildren(rule, 0, start, end);
    if (!children) {
      for (const altRule of rules) {
        if (altRule === rule) continue;
        const altChildren = this.reconstructChildren(altRule, 0, start, end);
        if (altChildren) {
          const node = this.buildNode(element, altRule, altChildren, start, end);
          this.reconstructionCache.set(cacheKey, node);
          return node;
        }
      }
      this.reconstructionCache.set(cacheKey, null);
      return null;
    }
    const node = this.buildNode(element, rule, children, start, end);
    this.reconstructionCache.set(cacheKey, node);
    return node;
  }

  private reconstructChildren(rule: EarleyRule, symIdx: number, start: number, end: number): SyntaxTreeNode[] | null {
    if (symIdx === rule.symbols.length) {
      return start === end ? [] : null;
    }
    const sym = rule.symbols[symIdx];
    const isLast = symIdx === rule.symbols.length - 1;
    if (!this.isNonterminal(sym)) {
      const matches = this.terminalMatches.get(start);
      if (!matches) return null;
      for (const match of matches) {
        if (match.element === sym) {
          const nextPos = start + 1;
          if (isLast && nextPos !== end) continue;
          const rest = this.reconstructChildren(rule, symIdx + 1, nextPos, end);
          if (rest !== null) {
            const leaf = this.createTerminalNode(sym, start, match.text);
            return [leaf, ...rest];
          }
        }
      }
      return null;
    } else {
      const minEnd = start;
      const maxEnd = isLast ? end : end;
      for (let mid = minEnd; mid <= maxEnd; mid++) {
        if (isLast && mid !== end) continue;
        const compKey = `${getElementId(sym)}:${start}:${mid}`;
        if (!this.completions.has(compKey)) continue;
        const childNode = this.reconstruct(sym, start, mid);
        if (!childNode) continue;
        const rest = this.reconstructChildren(rule, symIdx + 1, mid, end);
        if (rest !== null) {
          return [childNode, ...rest];
        }
      }
      return null;
    }
  }

  private buildNode(element: GrammarElement, rule: EarleyRule, children: SyntaxTreeNode[], start: number, end: number): SyntaxTreeNode {
    if (element instanceof Repetition) {
      children = this.flattenRepetition(children, element);
      if (element.max < Infinity && children.length > element.max) {
        children = children.slice(0, element.max);
      }
    }
    if (element instanceof Disjunction) {
      if (children.length === 1 && element.attributes.size === 0 && !element.finalizeFunction) {
        return children[0];
      }
    }
    if (element instanceof Optional && rule.symbols.length === 0) {
      const offset = this.positions[start] ?? 0;
      const loc = this.locationFromOffset(offset);
      return new SyntaxTreeNode(element, loc, loc, '', []);
    }
    const startOffset = this.positions[start] ?? 0;
    const endOffset = children.length > 0
      ? children[children.length - 1].end.index
      : (this.positions[end] ?? this.input.length);
    const text = this.input.slice(startOffset, endOffset);
    const startLoc = this.locationFromOffset(startOffset);
    const endLoc = this.locationFromOffset(endOffset);
    const node = new SyntaxTreeNode(element, startLoc, endLoc, text, children);
    for (const child of children) {
      child.parent = node;
    }
    this.evaluateAttributes(node);
    return this.finalizeNode(node);
  }

  private createTerminalNode(element: GrammarElement, chartPos: number, text: string): SyntaxTreeNode {
    const startOffset = this.positions[chartPos] ?? 0;
    const endOffset = startOffset + text.length;
    const startLoc = this.locationFromOffset(startOffset);
    const endLoc = this.locationFromOffset(endOffset);
    const node = new SyntaxTreeNode(element, startLoc, endLoc, text, []);
    this.evaluateAttributes(node);
    return this.finalizeNode(node);
  }

  private cloneTree(node: SyntaxTreeNode): SyntaxTreeNode {
    const children = node.children.map(c => this.cloneTree(c));
    const clone = new SyntaxTreeNode(node.element, node.start, node.end, node.text, children);
    for (const child of children) {
      child.parent = clone;
    }
    for (const [name] of node.element.attributes) {
      clone[name] = node[name];
    }
    return clone;
  }

  private flattenRepetition(children: SyntaxTreeNode[], rep: Repetition): SyntaxTreeNode[] {
    const result: SyntaxTreeNode[] = [];
    this.flattenRepHelper(children, rep, result);
    if (rep.delimiter && !rep.includeDelimiter) {
      return result.filter(c => c.element !== rep.delimiter);
    }
    return result;
  }

  private flattenRepHelper(children: SyntaxTreeNode[], rep: Repetition, result: SyntaxTreeNode[]): void {
    for (const child of children) {
      if (child.element === rep && child.children.length > 0) {
        this.flattenRepHelper(child.children, rep, result);
      } else {
        result.push(child);
      }
    }
  }

  private disambiguateRules(element: GrammarElement, rules: EarleyRule[], start: number, end: number): EarleyRule | null {
    if (rules.length === 0) return null;
    if (rules.length === 1) return rules[0];
    const cacheKey = `${getElementId(element)}:${start}:${end}`;
    const cached = this.disambiguationCache.get(cacheKey);
    if (cached) return cached;
    if (this.grammar.precedenceLevels.length > 0) {
      const result = this.disambiguateByPrecedence(element, rules, start, end);
      if (result) {
        this.disambiguationCache.set(cacheKey, result);
        return result;
      }
    }
    let best = rules[0];
    for (let i = 1; i < rules.length; i++) {
      if (rules[i].altIndex < best.altIndex) {
        best = rules[i];
      }
    }
    this.disambiguationCache.set(cacheKey, best);
    return best;
  }

  private disambiguateByPrecedence(element: GrammarElement, rules: EarleyRule[], start: number, end: number): EarleyRule | null {
    const ruleInfos: { rule: EarleyRule; level: number; assoc: 'left' | 'right' | 'none' }[] = [];
    for (const rule of rules) {
      const info = this.getOperatorInfo(rule);
      if (info) {
        ruleInfos.push({ rule, level: info.level, assoc: info.assoc });
      }
    }
    if (ruleInfos.length === 0) return null;
    if (ruleInfos.length < rules.length) {
      if (start + 1 < end) {
        ruleInfos.sort((a, b) => a.level - b.level);
        return ruleInfos[0].rule;
      }
      return null;
    }
    const allSameLevel = ruleInfos.every(r => r.level === ruleInfos[0].level);
    if (allSameLevel) {
      return ruleInfos[0].rule;
    }
    ruleInfos.sort((a, b) => a.level - b.level);
    return ruleInfos[0].rule;
  }

  private getOperatorInfo(rule: EarleyRule): { level: number; assoc: 'left' | 'right' | 'none' } | null {
    const actualSymbols = rule.symbols.length === 1 && rule.symbols[0] instanceof Phrase
      ? (rule.symbols[0] as Phrase).elements
      : rule.symbols;
    for (const sym of actualSymbols) {
      for (let level = 0; level < this.grammar.precedenceLevels.length; level++) {
        const precLevel = this.grammar.precedenceLevels[level];
        if (precLevel.operators.includes(sym)) {
          return { level, assoc: precLevel.associativity };
        }
      }
    }
    return null;
  }

  private evaluateAttributes(node: SyntaxTreeNode): void {
    for (const [name, def] of node.element.attributes) {
      if (def.evaluate) {
        node[name] = def.evaluate(node);
      }
    }
  }

  private finalizeNode(node: SyntaxTreeNode): SyntaxTreeNode {
    if (node.element.finalizeFunction) {
      const result = node.element.finalizeFunction(node);
      if (result instanceof SyntaxTreeNode) {
        result.parent = node.parent;
        return result;
      }
    }
    return node;
  }

  private describeTerminal(element: GrammarElement): string {
    if (element instanceof Terminal) {
      if (typeof element.pattern === 'string') {
        return `'${element.pattern}'`;
      }
      return element.name ?? `/${element.pattern.source}/`;
    }
    if (element instanceof SpecialTerminal) {
      return element.kind;
    }
    return element.name ?? 'unknown';
  }
}

function __parse(grammar: Grammar, input: string): ParseResult {
  const target = grammar.target;
  if (!target) {
    throw new Error('No target element specified.');
  }
  return new EarleyParser(grammar, input, target).parse();
}

function __parseExtended(grammar: Grammar, input: string, extensions: Map<GrammarElement, GrammarElement[]>): ParseResult {
  const target = grammar.target;
  if (!target) {
    throw new Error('No target element specified.');
  }
  return new EarleyParser(grammar, input, target, extensions).parse();
}


// ─── Grammar Definitions ────────────────────────────────────────────────────

function makeInt(n) {
return { kind: 'Bits', length: 64, data: BigInt(n) };
}
function makeBits(length, data) {
return { kind: 'Bits', length, data: typeof data === 'number' ? BigInt(data) : data };
}
function stringToBits(s) {
const enc = new TextEncoder();
const bytes = enc.encode(s);
let data = 0n;
for (let i = bytes.length - 1; i >= 0; i--) {
data = (data << 8n) | BigInt(bytes[i]);
}
return makeBits(bytes.length * 8, data);
}
function makeParam(position, name) {
return { kind: 'Param', position, owner: null, _name: name };
}
function makeExpr(fn, args) {
return { kind: 'Expression', fn, args, memo: new Map() };
}
function makeComposedFn(params, body) {
const fn = { kind: 'ComposedFunction', params, body };
for (const p of params) p.owner = fn;
return fn;
}
function makeContext() {
return { kind: 'Context', bindings: new Map(), bindingList: [] };
}
function prim(name) {
return { kind: 'PrimitiveFunction', name, fn: null, lazy: name === 'eval_if' };
}
function cloneVal(v, seen) {
if (!v || typeof v !== 'object') return v;
if (seen.has(v)) return seen.get(v);
if (v.kind === 'Param') {
const c = makeParam(v.position, v._name);
seen.set(v, c);
return c;
}
if (v.kind === 'Expression') {
const c = makeExpr(cloneVal(v.fn, seen), v.args.map(a => cloneVal(a, seen)));
seen.set(v, c);
return c;
}
// Clone into zero-param thunks (if-then-else branches) so params can be claimed
if (v.kind === 'ComposedFunction' && v.params.length === 0) {
const c = makeComposedFn([], cloneVal(v.body, seen));
seen.set(v, c);
return c;
}
return v;
}
function collectParams(v, out, seen) {
if (!v || seen.has(v)) return;
seen.add(v);
if (v.kind === 'Param' && v.owner === null) out.push(v);
if (v.kind === 'Expression') {
collectParams(v.fn, out, seen);
for (const a of v.args) collectParams(a, out, seen);
}
// Descend into zero-param thunks (if-then-else branches) to claim their params
if (v.kind === 'ComposedFunction' && v.params.length === 0) {
collectParams(v.body, out, seen);
}
}
function buildFn(paramNames, body) {
const cloned = cloneVal(body, new Map());
const paramValues = [];
collectParams(cloned, paramValues, new Set());
const matched = [];
const seenPos = new Set();
for (const p of paramValues) {
const idx = paramNames.indexOf(p._name);
if (idx >= 0) {
p.position = idx;
if (!seenPos.has(idx)) {
matched.push(p);
seenPos.add(idx);
}
}
}
matched.sort((a, b) => a.position - b.position);
return makeComposedFn(matched, cloned);
}
function substName(v, name, replacement) {
if (v.kind === 'Param' && v._name === name) return replacement;
if (v.kind === 'Expression') {
const nf = substName(v.fn, name, replacement);
const na = v.args.map(a => substName(a, name, replacement));
if (nf === v.fn && na.every((a, i) => a === v.args[i])) return v;
return makeExpr(nf, na);
}
if (v.kind === 'ComposedFunction') {
if (v.params.some(p => p._name === name)) return v;
const nb = substName(v.body, name, replacement);
if (nb === v.body) return v;
const nfn = { kind: 'ComposedFunction', params: v.params, body: nb };
for (const p of nfn.params) p.owner = nfn;
return nfn;
}
return v;
}
function bind(ctx, name, value) {
const b = { key: name, value, isUse: false };
ctx.bindings.set(name, b);
ctx.bindingList.push(b);
}
function extractString(text) {
const inner = text.slice(1, -1);
let result = '';
for (let i = 0; i < inner.length; i++) {
if (inner[i] === '\\' && i + 1 < inner.length) {
i++;
const c = inner[i];
result += c === 'n' ? '\n' : c === 't' ? '\t' : c === '\\' ? '\\' : c === '"' ? '"' : c;
} else {
result += inner[i];
}
}
return result;
}
function repChildren(repNode) {
return repNode.children.filter(
c => c.element !== repNode.element || c.children.length > 0
);
}
function buildFileCtx(repNode) {
const ctx = makeContext();
for (const child of repChildren(repNode)) {
const s = child.children[0];
if (s.binding) {
bind(ctx, s.binding.name, s.binding.value);
} else if (s.val !== undefined) {
ctx.bindingList.push({ key: null, value: s.val, isUse: false });
}
}
return ctx;
}
function buildBlock(repNode, lastExpr) {
// Collect bindings, then substitute each into the result and all later bindings
const bindings = [];
for (const child of repChildren(repNode)) {
const b = child.children[0];
if (b.binding) bindings.push({ name: b.binding.name, value: b.binding.value });
}
let result = lastExpr;
for (let i = 0; i < bindings.length; i++) {
const { name, value } = bindings[i];
// Substitute this binding into all subsequent binding values
for (let j = i + 1; j < bindings.length; j++) {
bindings[j].value = substName(bindings[j].value, name, value);
}
// Substitute into the final result
result = substName(result, name, value);
}
return result;
}

// ─── Grammar Construction ────────────────────────────────────────────────────

const __grammar = new Grammar({ whitespace: /[ \t]+/, comments: /\/\/[^\n]*/, blockIndent: true });

let __el_0, __el_1, __el_2, __el_3, __el_4, __el_5, __el_6, __el_7, __el_8, __el_9, __el_10, __el_11, __el_12, __el_13, __el_14, __el_15, __el_16, __el_17, __el_18, __el_19, __el_20, __el_21, __el_22, __el_23, __el_24, __el_25, __el_26, __el_27, __el_28, __el_29, __el_30, __el_31, __el_32, __el_33, __el_34, __el_35, __el_36, __el_37, __el_38, __el_39, __el_40, __el_41, __el_42, __el_43, __el_44, __el_45, __el_46, __el_47, __el_48, __el_49, __el_50, __el_51, __el_52, __el_53, __el_54, __el_55, __el_56, __el_57, __el_58, __el_59, __el_60, __el_61, __el_62, __el_63, __el_64, __el_65, __el_66, __el_67, __el_68, __el_69, __el_70, __el_71, __el_72, __el_73, __el_74, __el_75, __el_76, __el_77, __el_78, __el_79, __el_80, __el_81, __el_82, __el_83, __el_84, __el_85, __el_86, __el_87, __el_88, __el_89, __el_90, __el_91, __el_92, __el_93, __el_94, __el_95, __el_96, __el_97, __el_98, __el_99: any;
__el_9 = __grammar.terminal(/[a-zA-Z_][a-zA-Z0-9_]*/, "Ident");
__el_10 = __grammar.terminal("(");
__el_14 = __grammar.terminal(",");
__el_15 = __grammar.terminal(")");
__el_16 = __grammar.terminal(/=>/, "Arrow");
__el_19 = SpecialTerminal.of("EndOfLine");
__el_20 = SpecialTerminal.of("Indent");
__el_30 = __grammar.terminal(/=(?![>=])/, "Eq");
__el_40 = __grammar.terminal(/==/, "EqEq");
__el_43 = __grammar.terminal("+");
__el_46 = __grammar.terminal("*");
__el_49 = __grammar.terminal("-");
__el_61 = __grammar.terminal("if");
__el_62 = __grammar.terminal("then");
__el_63 = __grammar.terminal("else");
__el_65 = __grammar.terminal(/0[xX][0-9a-fA-F]+/, "HexInt");
__el_67 = __grammar.terminal(/0[bB][01]+/, "BinInt");
__el_69 = __grammar.terminal(/[0-9]+/, "Int");
__el_71 = __grammar.terminal(/"([^"\\]|\\.)*"/, "Str");
__el_75 = __grammar.terminal("/");
__el_77 = __grammar.terminal("%");
__el_82 = __grammar.terminal(/!=/, "BangEq");
__el_84 = __grammar.terminal(/<(?!=)/, "Lt");
__el_86 = __grammar.terminal(/>(?!=)/, "Gt");
__el_88 = __grammar.terminal(/<=/, "LtEq");
__el_90 = __grammar.terminal(/>=/, "GtEq");
__el_95 = SpecialTerminal.of("Unindent");
__el_0 = __grammar.disjunction([], "File");
__el_3 = __grammar.disjunction([], "StmtLine");
__el_5 = __grammar.disjunction([], "Statement");
__el_7 = __grammar.disjunction([], "NamedFnDecl");
__el_11 = __grammar.disjunction([], "ParamList");
__el_17 = __grammar.disjunction([], "FnBody");
__el_21 = __grammar.disjunction([], "Block");
__el_24 = __grammar.disjunction([], "BlockLine");
__el_26 = __grammar.disjunction([], "BlockBinding");
__el_28 = __grammar.disjunction([], "Assignment");
__el_31 = __grammar.disjunction([], "Expr");
__el_33 = __grammar.disjunction([], "LambdaExpr");
__el_38 = __grammar.disjunction([], "CompareExpr");
__el_41 = __grammar.disjunction([], "AddExpr");
__el_44 = __grammar.disjunction([], "MulExpr");
__el_47 = __grammar.disjunction([], "UnaryExpr");
__el_51 = __grammar.disjunction([], "CallExpr");
__el_53 = __grammar.disjunction([], "ArgList");
__el_57 = __grammar.disjunction([], "Primary");
__el_59 = __grammar.disjunction([], "IfExpr");
__el_99 = __grammar.phrase([__el_5]);
__el_98 = __grammar.phrase([__el_31]);
__el_97 = __grammar.phrase([__el_28]);
__el_96 = __grammar.phrase([__el_31]);
__el_94 = __grammar.phrase([__el_31]);
__el_93 = __grammar.phrase([__el_26]);
__el_92 = __grammar.phrase([__el_7]);
__el_91 = __grammar.phrase([__el_41]);
__el_89 = __grammar.phrase([__el_38, __el_90, __el_41]);
__el_87 = __grammar.phrase([__el_38, __el_88, __el_41]);
__el_85 = __grammar.phrase([__el_38, __el_86, __el_41]);
__el_83 = __grammar.phrase([__el_38, __el_84, __el_41]);
__el_81 = __grammar.phrase([__el_38, __el_82, __el_41]);
__el_80 = __grammar.phrase([__el_44]);
__el_79 = __grammar.phrase([__el_41, __el_49, __el_44]);
__el_78 = __grammar.phrase([__el_47]);
__el_76 = __grammar.phrase([__el_44, __el_77, __el_47]);
__el_74 = __grammar.phrase([__el_44, __el_75, __el_47]);
__el_73 = __grammar.phrase([__el_9]);
__el_72 = __grammar.phrase([__el_10, __el_31, __el_15]);
__el_70 = __grammar.phrase([__el_71]);
__el_68 = __grammar.phrase([__el_69]);
__el_66 = __grammar.phrase([__el_67]);
__el_64 = __grammar.phrase([__el_65]);
__el_60 = __grammar.phrase([__el_61, __el_31, __el_62, __el_31, __el_63, __el_31]);
__el_58 = __grammar.phrase([__el_59]);
__el_56 = __grammar.phrase([__el_57]);
__el_55 = __grammar.repeat(__el_31, { delimiter: __el_14 });
__el_54 = __grammar.phrase([__el_55]);
__el_52 = __grammar.phrase([__el_51, __el_10, __el_53, __el_15]);
__el_50 = __grammar.phrase([__el_51]);
__el_48 = __grammar.phrase([__el_49, __el_47]);
__el_45 = __grammar.phrase([__el_44, __el_46, __el_47]);
__el_42 = __grammar.phrase([__el_41, __el_43, __el_44]);
__el_39 = __grammar.phrase([__el_38, __el_40, __el_41]);
__el_37 = __grammar.phrase([__el_38]);
__el_36 = __grammar.phrase([__el_10, __el_15, __el_16, __el_17]);
__el_35 = __grammar.phrase([__el_10, __el_11, __el_15, __el_16, __el_17]);
__el_34 = __grammar.phrase([__el_9, __el_16, __el_17]);
__el_32 = __grammar.phrase([__el_33]);
__el_29 = __grammar.phrase([__el_9, __el_30, __el_31]);
__el_27 = __grammar.phrase([__el_28]);
__el_25 = __grammar.phrase([__el_26, __el_19]);
__el_23 = __grammar.repeat(__el_24);
__el_22 = __grammar.phrase([__el_23, __el_31]);
__el_18 = __grammar.phrase([__el_19, __el_20, __el_21, __el_19, __el_95]);
__el_13 = __grammar.repeat(__el_9, { delimiter: __el_14 });
__el_12 = __grammar.phrase([__el_13]);
__el_8 = __grammar.phrase([__el_9, __el_10, __el_11, __el_15, __el_16, __el_17]);
__el_6 = __grammar.phrase([__el_7]);
__el_4 = __grammar.phrase([__el_5, __el_19]);
__el_2 = __grammar.repeat(__el_3);
__el_1 = __grammar.phrase([__el_2]);

__el_0.add(__el_1);
__el_3.add(__el_4);
__el_3.add(__el_99);
__el_5.add(__el_6);
__el_5.add(__el_97);
__el_5.add(__el_98);
__el_7.add(__el_8);
__el_11.add(__el_12);
__el_17.add(__el_18);
__el_17.add(__el_96);
__el_21.add(__el_22);
__el_21.add(__el_94);
__el_24.add(__el_25);
__el_24.add(__el_93);
__el_26.add(__el_27);
__el_26.add(__el_92);
__el_28.add(__el_29);
__el_31.add(__el_32);
__el_31.add(__el_58);
__el_31.add(__el_37);
__el_33.add(__el_34);
__el_33.add(__el_35);
__el_33.add(__el_36);
__el_38.add(__el_39);
__el_38.add(__el_81);
__el_38.add(__el_83);
__el_38.add(__el_85);
__el_38.add(__el_87);
__el_38.add(__el_89);
__el_38.add(__el_91);
__el_41.add(__el_42);
__el_41.add(__el_79);
__el_41.add(__el_80);
__el_44.add(__el_45);
__el_44.add(__el_74);
__el_44.add(__el_76);
__el_44.add(__el_78);
__el_47.add(__el_48);
__el_47.add(__el_50);
__el_51.add(__el_52);
__el_51.add(__el_56);
__el_53.add(__el_54);
__el_57.add(__el_64);
__el_57.add(__el_66);
__el_57.add(__el_68);
__el_57.add(__el_70);
__el_57.add(__el_72);
__el_57.add(__el_73);
__el_59.add(__el_60);

__el_1.attribute("ctx", Object, function eval_0_ctx(node) { return (buildFileCtx(node.children[0])); });
__el_4.attribute("binding", Object, function eval_1_binding(node) { return (node.children[0].binding); });
__el_4.attribute("val", Object, function eval_1_val(node) { return (node.children[0].val); });
__el_6.attribute("binding", Object, function eval_3_binding(node) { return (node.children[0].binding); });
__el_6.attribute("val", Object, function eval_3_val(node) { return (undefined); });
__el_8.attribute("binding", Object, function eval_7_binding(node) { return ({ name: node.children[0].text, value: buildFn(node.children[2].names, node.children[5].val) }); });
__el_12.attribute("names", Object, function eval_8_names(node) { return (repChildren(node.children[0]).map(c => c.text)); });
__el_18.attribute("val", Object, function eval_14_val(node) { return (node.children[2].val); });
__el_22.attribute("val", Object, function eval_16_val(node) { return (buildBlock(node.children[0], node.children[1].val)); });
__el_25.attribute("binding", Object, function eval_18_binding(node) { return (node.children[0].binding); });
__el_27.attribute("binding", Object, function eval_20_binding(node) { return (node.children[0].binding); });
__el_29.attribute("binding", Object, function eval_6_binding(node) { return ({ name: node.children[0].text, value: node.children[2].val }); });
__el_32.attribute("val", Object, function eval_9_val(node) { return (node.children[0].val); });
__el_34.attribute("val", Object, function eval_11_val(node) { return (buildFn([node.children[0].text], node.children[2].val)); });
__el_35.attribute("val", Object, function eval_12_val(node) { return (buildFn(node.children[1].names, node.children[4].val)); });
__el_36.attribute("val", Object, function eval_13_val(node) { return (buildFn([], node.children[3].val)); });
__el_37.attribute("val", Object, function eval_10_val(node) { return (node.children[0].val); });
__el_39.attribute("val", Object, function eval_22_val(node) { return (makeExpr(prim('bits_eq'), [node.children[0].val, node.children[2].val])); });
__el_42.attribute("val", Object, function eval_29_val(node) { return (makeExpr(prim('bits_add'), [node.children[0].val, node.children[2].val])); });
__el_45.attribute("val", Object, function eval_32_val(node) { return (makeExpr(prim('bits_mul'), [node.children[0].val, node.children[2].val])); });
__el_48.attribute("val", Object, function eval_36_val(node) { return (makeExpr(prim('bits_sub'), [makeInt(0), node.children[1].val])); });
__el_50.attribute("val", Object, function eval_37_val(node) { return (node.children[0].val); });
__el_52.attribute("val", Object, function eval_38_val(node) { return (makeExpr(node.children[0].val, node.children[2].vals)); });
__el_54.attribute("vals", Object, function eval_40_vals(node) { return (repChildren(node.children[0]).map(c => c.val)); });
__el_56.attribute("val", Object, function eval_39_val(node) { return (node.children[0].val); });
__el_58.attribute("val", Object, function eval_41_val(node) { return (node.children[0].val); });
__el_60.attribute("val", Object, function eval_48_val(node) { return (makeExpr(prim('eval_if'), [node.children[1].val, makeComposedFn([], node.children[3].val), makeComposedFn([], node.children[5].val)])); });
__el_64.attribute("val", Object, function eval_42_val(node) { return (makeInt(parseInt(node.children[0].text, 16))); });
__el_66.attribute("val", Object, function eval_43_val(node) { return (makeInt(Number(node.children[0].text))); });
__el_68.attribute("val", Object, function eval_44_val(node) { return (makeInt(parseInt(node.children[0].text, 10))); });
__el_70.attribute("val", Object, function eval_45_val(node) { return (stringToBits(extractString(node.children[0].text))); });
__el_72.attribute("val", Object, function eval_46_val(node) { return (node.children[1].val); });
__el_73.attribute("val", Object, function eval_47_val(node) { return (makeParam(-1, node.children[0].text)); });
__el_74.attribute("val", Object, function eval_33_val(node) { return (makeExpr(prim('bits_div'), [node.children[0].val, node.children[2].val])); });
__el_76.attribute("val", Object, function eval_34_val(node) { return (makeExpr(prim('bits_mod'), [node.children[0].val, node.children[2].val])); });
__el_78.attribute("val", Object, function eval_35_val(node) { return (node.children[0].val); });
__el_79.attribute("val", Object, function eval_30_val(node) { return (makeExpr(prim('bits_sub'), [node.children[0].val, node.children[2].val])); });
__el_80.attribute("val", Object, function eval_31_val(node) { return (node.children[0].val); });
__el_81.attribute("val", Object, function eval_23_val(node) { return (makeExpr(prim('bits_eq'), [makeExpr(prim('bits_eq'), [node.children[0].val, node.children[2].val]), makeInt(0)])); });
__el_83.attribute("val", Object, function eval_24_val(node) { return (makeExpr(prim('bits_lt'), [node.children[0].val, node.children[2].val])); });
__el_85.attribute("val", Object, function eval_25_val(node) { return (makeExpr(prim('bits_gt'), [node.children[0].val, node.children[2].val])); });
__el_87.attribute("val", Object, function eval_26_val(node) { return (makeExpr(prim('bits_lte'), [node.children[0].val, node.children[2].val])); });
__el_89.attribute("val", Object, function eval_27_val(node) { return (makeExpr(prim('bits_gte'), [node.children[0].val, node.children[2].val])); });
__el_91.attribute("val", Object, function eval_28_val(node) { return (node.children[0].val); });
__el_92.attribute("binding", Object, function eval_21_binding(node) { return (node.children[0].binding); });
__el_93.attribute("binding", Object, function eval_19_binding(node) { return (node.children[0].binding); });
__el_94.attribute("val", Object, function eval_17_val(node) { return (node.children[0].val); });
__el_96.attribute("val", Object, function eval_15_val(node) { return (node.children[0].val); });
__el_97.attribute("binding", Object, function eval_4_binding(node) { return (node.children[0].binding); });
__el_97.attribute("val", Object, function eval_4_val(node) { return (undefined); });
__el_98.attribute("binding", Object, function eval_5_binding(node) { return (null); });
__el_98.attribute("val", Object, function eval_5_val(node) { return (node.children[0].val); });
__el_99.attribute("binding", Object, function eval_2_binding(node) { return (node.children[0].binding); });
__el_99.attribute("val", Object, function eval_2_val(node) { return (node.children[0].val); });

__grammar.target = __el_0;

// ─── Public API ─────────────────────────────────────────────────────────────

export function parse(input: string): ParseResult {
  return __parse(__grammar, input);
}

export function parseWithExtensions(input: string, extensions: Map<any, any[]>): ParseResult {
  return __parseExtended(__grammar, input, extensions);
}

// Grammar element classes and types (for building extensions)
export { Grammar, GrammarElement, Terminal, Phrase, Disjunction, SyntaxTreeNode };
export type { ParseResult };

// Base grammar instance (immutable — extensions create new alternatives, not modify this)
export { __grammar as baseGrammar };

// Parser helpers for building attribute functions in grammar extensions
export {
  makeExpr as parserMakeExpr,
  makeParam as parserMakeParam,
  makeInt as parserMakeInt,
  makeComposedFn as parserMakeComposedFn,
  prim as parserPrim,
  buildFn as parserBuildFn,
  substName as parserSubstName,
  stringToBits as parserStringToBits,
  makeContext as parserMakeContext,
  bind as parserBind,
};